name       : python-genty
version    : 1.3.2
release    : 4
source     :
    - https://github.com/box/genty/releases/download/v1.3.2/genty-1.3.2.tar.gz : 2e3f5bfe2d3a757c0e2a48ac4716bca42d3b76d9cfc3401ef606635049c35dab
license    : Apache-2.0
component  : programming.python
summary    : Genty, stands for "generate tests". It promotes generative testing, where
    a single test can execute over a variety of input
description: |
    Genty, pronounced "gen-tee", stands for "generate tests". It promotes generative testing, where a single test can execute over a variety of input. Genty makes this a breeze.
builddeps  :
    - python-mock
    - python-setuptools
rundeps    :
    - python-six
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
